-- Datos ampliados de los espacios escénicos (fichas completas).
--
-- Rellena las columnas nuevas de 20261009150000 para los 138 espacios
-- publicados en Canarias y Madrid. Requiere esa migración aplicada antes.
--
-- Fuentes:
--   · Dirección, código postal, teléfono, correo, accesibilidad y titularidad:
--     OpenStreetMap (© colaboradores de OpenStreetMap, ODbL).
--   · Año de inauguración, arquitectura, aforo e identificador: Wikidata (CC0).
--   · Fotos: Wikimedia Commons, con autor, licencia y página de origen.
--   · Descripciones: redactadas por ObrasDeTeatro a partir de esos datos
--     (descripcion_origen = 'ia_revisada').
--
-- Criterios de privacidad: solo teléfonos fijos y correos generales del
-- espacio. Se descartan móviles y buzones de personas o cargos.
--
-- Solo actualiza filas existentes por slug; es idempotente.

update public.espacios_escenicos set telefono = '+34 928 49 17 70', wikidata_id = 'Q3629501', arquitecto = 'Óscar Tusquets Blanca', aforo = 1656, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Auditorio_alfredo_kraus_las_palmas_de_gran_canaria.jpg/1280px-Auditorio_alfredo_kraus_las_palmas_de_gran_canaria.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Auditorio_alfredo_kraus_las_palmas_de_gran_canaria.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Pepelopex', descripcion = 'Auditorio proyectado por Óscar Tusquets junto a la playa de Las Canteras, en Las Palmas de Gran Canaria. Lleva el nombre del tenor grancanario Alfredo Kraus y es sede habitual de la Orquesta Filarmónica de Gran Canaria. Su sala sinfónica se abre al océano con un gran ventanal.', descripcion_origen = 'ia_revisada' where slug = 'auditorio-alfredo-kraus';
update public.espacios_escenicos set direccion = 'Calle Norias', codigo_postal = '28220' where slug = 'auditorio-alfredo-kraus-majadahonda';
update public.espacios_escenicos set direccion = 'Calle Universidad de La Laguna', titularidad = 'publica' where slug = 'auditorio-de-adeje';
update public.espacios_escenicos set direccion = 'Calle Alcalde Jaime del Castillo', codigo_postal = '35620', accesibilidad = 'parcial', titularidad = 'publica' where slug = 'auditorio-de-gran-tarajal';
update public.espacios_escenicos set wikidata_id = 'Q28964', anio_inauguracion = 2003, arquitecto = 'Santiago Calatrava', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Auditorio_de_Tenerife_2015_%2850MP%29.jpg/1280px-Auditorio_de_Tenerife_2015_%2850MP%29.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Auditorio_de_Tenerife_2015_(50MP).jpg', imagen_licencia = 'CC BY-SA 3.0 de', imagen_autor = 'Thomas Wolf, www.foto-tw.de', descripcion = 'Obra de Santiago Calatrava inaugurada en 2003 junto al mar, en Santa Cruz de Tenerife, y reconocible por su gran ala de hormigón blanco. Es sede de la Orquesta Sinfónica de Tenerife y acoge ópera, conciertos y artes escénicas.', descripcion_origen = 'ia_revisada' where slug = 'auditorio-de-tenerife-adan-martin';
update public.espacios_escenicos set direccion = 'Camino de las Huertas', telefono = '+34 91 7628300', titularidad = 'publica' where slug = 'auditorio-el-torreon';
update public.espacios_escenicos set direccion = 'Calle Ramiro de Maeztu', codigo_postal = '35600' where slug = 'auditorio-insular-de-fuerteventura';
update public.espacios_escenicos set direccion = 'Calle Emilio Ley 4', codigo_postal = '35005', accesibilidad = 'si', titularidad = 'publica' where slug = 'auditorio-jose-antonio-ramos';
update public.espacios_escenicos set direccion = 'Calle de Lope de Vega 38', codigo_postal = '28014', accesibilidad = 'si' where slug = 'auditorio-marcelino-camacho';
update public.espacios_escenicos set anio_inauguracion = 1981 where slug = 'auditorio-municipal-alfonso-garcia-ramos';
update public.espacios_escenicos set titularidad = 'publica' where slug = 'auditorio-municipal-de-corralejo';
update public.espacios_escenicos set direccion = 'Calle Real 158', codigo_postal = '38370' where slug = 'auditorio-municipal-de-la-matanza-de-acentejo';
update public.espacios_escenicos set direccion = 'Calle Monte de Montjuich 7', codigo_postal = '28031', titularidad = 'publica' where slug = 'auditorio-municipal-las-trece-rosas';
update public.espacios_escenicos set direccion = 'Calle de la Fundición', codigo_postal = '28522', wikidata_id = 'Q52667346', anio_inauguracion = 2004, aforo = 1023, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Auditorio_Pilar_Bardem_%28Rivas-Vaciamadrid%29_02.jpg/1280px-Auditorio_Pilar_Bardem_%28Rivas-Vaciamadrid%29_02.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Auditorio_Pilar_Bardem_(Rivas-Vaciamadrid)_02.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Auditorio municipal de Rivas-Vaciamadrid inaugurado en 2004, con más de mil localidades. Lleva el nombre de la actriz Pilar Bardem.', descripcion_origen = 'ia_revisada' where slug = 'auditorio-pilar-bardem';
update public.espacios_escenicos set anio_inauguracion = 1957, descripcion = 'Auditorio de La Orotava que lleva el nombre del compositor Teobaldo Power, autor de los «Cantos canarios». Programa música, teatro y danza.', descripcion_origen = 'ia_revisada' where slug = 'auditorio-teobaldo-power';
update public.espacios_escenicos set direccion = 'Calle de las Canarias 16', codigo_postal = '28045', telefono = '+34 913 60 01 93' where slug = 'bululu-2120';
update public.espacios_escenicos set direccion = 'Alameda de Colón 1', codigo_postal = '35002', anio_inauguracion = 1990, descripcion = 'Centro cultural situado en la Alameda de Colón, en el centro de Las Palmas de Gran Canaria, abierto en 1990. Programa teatro, música, cine y exposiciones.', descripcion_origen = 'ia_revisada' where slug = 'centro-cultural-cicca';
update public.espacios_escenicos set titularidad = 'publica' where slug = 'centro-cultural-paco-rabal';
update public.espacios_escenicos set direccion = 'Paseo de las Delicias 61', codigo_postal = '28045', titularidad = 'privada' where slug = 'espacio-ibercaja-delicias';
update public.espacios_escenicos set direccion = 'Calle de Primitiva Gañán 5', codigo_postal = '28026', wikidata_id = 'Q16913140' where slug = 'exlimite';
update public.espacios_escenicos set direccion = 'Cuesta de San Vicente 44', codigo_postal = '28008', telefono = '+34 918 669 393', accesibilidad = 'si' where slug = 'gran-teatro-caixabank-principe-pio';
update public.espacios_escenicos set direccion = 'Calle de Lavapiés 9', codigo_postal = '28012', email = 'info@laescaleradejacob.es' where slug = 'la-escalera-de-jacob';
update public.espacios_escenicos set direccion = 'Calle de Francisca Conde 7' where slug = 'liberarte';
update public.espacios_escenicos set direccion = 'Calle de Loreto Prado y Enrique Chicote 9', codigo_postal = '28004', telefono = '+34 915 218 874' where slug = 'microteatro';
update public.espacios_escenicos set direccion = 'Camino de las Huertas 42', codigo_postal = '28224', telefono = '+34 917 62 83 00', titularidad = 'publica' where slug = 'mira-teatro';
update public.espacios_escenicos set direccion = 'Calle de Palos de la Frontera 5', codigo_postal = '28012' where slug = 'nave-73';
update public.espacios_escenicos set telefono = '+34 91 435 34 03', accesibilidad = 'si', wikidata_id = 'Q9051124', anio_inauguracion = 1924, arquitecto = 'Luis Ferrero' where slug = 'nuevo-teatro-alcala';
update public.espacios_escenicos set direccion = 'Calle de los Mancebos 4', codigo_postal = '28005' where slug = 'off-de-la-latina';
update public.espacios_escenicos set accesibilidad = 'no' where slug = 'orfeon-la-paz';
update public.espacios_escenicos set accesibilidad = 'si', titularidad = 'privada' where slug = 'piramide-de-arona';
update public.espacios_escenicos set direccion = 'Calle de Ercilla 29' where slug = 'plotpoint';
update public.espacios_escenicos set direccion = 'Calle de la Explanada 14', codigo_postal = '28040', telefono = '+34915350570' where slug = 'replika-teatro';
update public.espacios_escenicos set titularidad = 'privada' where slug = 'sala-arapiles-16';
update public.espacios_escenicos set accesibilidad = 'no' where slug = 'sala-azarte';
update public.espacios_escenicos set direccion = 'Calle de Galileo 100', codigo_postal = '28015', telefono = '+34 91 534 75 57', accesibilidad = 'no' where slug = 'sala-galileo-galilei';
update public.espacios_escenicos set telefono = '+34 928432180' where slug = 'sala-insular-de-teatro';
update public.espacios_escenicos set direccion = 'Calle de Palafox 14', codigo_postal = '28010', telefono = '+34 91 521 71 65' where slug = 'sala-mala-sana';
update public.espacios_escenicos set direccion = 'Calle del Doctor Fourquet 31', codigo_postal = '28012', telefono = '+34 91 528 95 04', wikidata_id = 'Q21573843' where slug = 'sala-mirador';
update public.espacios_escenicos set direccion = 'Calle de Dolores Armengot 31', codigo_postal = '28025', telefono = '+34914618334' where slug = 'sala-tarambana';
update public.espacios_escenicos set direccion = 'Calle de la Paz 11', codigo_postal = '28012', telefono = '+34 911 231 099', email = 'info.madrid@umusic-hotels.com', accesibilidad = 'si', titularidad = 'privada', wikidata_id = 'Q6139586', arquitecto = 'Fernando Roch Pena', aforo = 898, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Teatro_Alb%C3%A9niz_%28Madrid%29_01.jpg/1280px-Teatro_Alb%C3%A9niz_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Alb%C3%A9niz_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro de la calle de la Paz, junto a la Puerta del Sol, proyectado por Fernando Roch Pena. Hoy forma parte del complejo del hotel UMusic Madrid.', descripcion_origen = 'ia_revisada' where slug = 'teatro-albeniz';
update public.espacios_escenicos set direccion = 'Calle de Alcalá 20', codigo_postal = '28014', accesibilidad = 'no', wikidata_id = 'Q6139588', arquitecto = 'Eduardo Lozano Lardet / Eduardo Sánchez Eznarriaga', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/6/63/Teatro_Alc%C3%A1zar_Madrid.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Alc%C3%A1zar_Madrid.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'William Avery', descripcion = 'Teatro de la calle de Alcalá, a pocos pasos de la Puerta del Sol, con edificio de Eduardo Lozano Lardet y Eduardo Sánchez Eznarriaga.', descripcion_origen = 'ia_revisada' where slug = 'teatro-alcazar';
update public.espacios_escenicos set direccion = 'Calle del Pez 10', codigo_postal = '28004', wikidata_id = 'Q6139590', aforo = 208, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Teatro_Alfil_%28Madrid%29_01.jpg/1280px-Teatro_Alfil_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Alfil_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0 es', imagen_autor = 'Luis García (Zaqarbal)' where slug = 'teatro-alfil';
update public.espacios_escenicos set direccion = 'Paseo del General Martínez Campos 9', wikidata_id = 'Q63161974' where slug = 'teatro-amaya';
update public.espacios_escenicos set direccion = 'Calle de San Bernardo 5', codigo_postal = '28013', telefono = '+34 915 470 430', wikidata_id = 'Q21483924' where slug = 'teatro-arlequin-gran-via';
update public.espacios_escenicos set direccion = 'Calle de Abel 1', codigo_postal = '28039', telefono = '+34 915 331 565', email = 'info@teatroasura.com' where slug = 'teatro-asura';
update public.espacios_escenicos set direccion = 'Calle de Barceló 11', codigo_postal = '28004', email = 'info@teatrobarcelo.com', wikidata_id = 'Q5769468', anio_inauguracion = 1930, arquitecto = 'Luis Gutiérrez Soto', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Teatro_Barcel%C3%B3%2C_Madrid.JPG/1280px-Teatro_Barcel%C3%B3%2C_Madrid.JPG', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Barcel%C3%B3,_Madrid.JPG', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Asqueladd', descripcion = 'Edificio racionalista de 1930 proyectado por Luis Gutiérrez Soto en la calle de Barceló. A lo largo de su historia ha sido teatro, cine y sala de fiestas.', descripcion_origen = 'ia_revisada' where slug = 'teatro-barcelo';
update public.espacios_escenicos set direccion = 'Calle del Marqués de Casa Riera 2', codigo_postal = '28014', wikidata_id = 'Q6139609', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Teatro_Bellas_Artes_%28Madrid%29_01.jpg/1280px-Teatro_Bellas_Artes_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Bellas_Artes_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro con entrada por la calle del Marqués de Casa Riera, en el edificio del Círculo de Bellas Artes.', descripcion_origen = 'ia_revisada' where slug = 'teatro-bellas-artes';
update public.espacios_escenicos set direccion = 'Calle del Doctor Cortezo 1', codigo_postal = '28012', wikidata_id = 'Q6381861', arquitecto = 'Eduardo Sánchez Eznarriaga', aforo = 1000, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Teatro_Calder%C3%B3n_%28Madrid%29_02.jpg/1280px-Teatro_Calder%C3%B3n_%28Madrid%29_02.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Calder%C3%B3n_(Madrid)_02.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Gran teatro de la calle del Doctor Cortezo, junto a la plaza de Jacinto Benavente, proyectado por Eduardo Sánchez Eznarriaga. Con alrededor de mil localidades, es uno de los mayores teatros de Madrid.', descripcion_origen = 'ia_revisada' where slug = 'teatro-calderon';
update public.espacios_escenicos set wikidata_id = 'Q9082133', anio_inauguracion = 1866, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/8/86/Teatro_Chico.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Chico.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Wesisnay', descripcion = 'Pequeño teatro de Santa Cruz de La Palma inaugurado en 1866, uno de los más antiguos de Canarias. Acoge teatro, música y proyecciones de cine.', descripcion_origen = 'ia_revisada' where slug = 'teatro-chico';
update public.espacios_escenicos set direccion = 'Calle Infanta Isabel 9' where slug = 'teatro-cine-fajardo';
update public.espacios_escenicos set wikidata_id = 'Q6139658', anio_inauguracion = 1918, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/At_La_Palma_2023_459.jpg/1280px-At_La_Palma_2023_459.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:At_La_Palma_2023_459.jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Mike Peel', descripcion = 'Teatro histórico de Santa Cruz de La Palma, con edificio de 1918 heredero de un antiguo teatro circo. Acoge teatro, música y actos culturales de la isla.', descripcion_origen = 'ia_revisada' where slug = 'teatro-circo-de-marte';
update public.espacios_escenicos set wikidata_id = 'Q5121553', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Teatro_Circo_Price_-_01.jpg/1280px-Teatro_Circo_Price_-_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Circo_Price_-_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Carlos Delgado', descripcion = 'Espacio municipal dedicado al circo y las artes escénicas, heredero del circo que fundó en el siglo XIX el jinete Thomas Price. Su sede actual, en la ronda de Atocha, abrió en 2007 en un antiguo recinto industrial.', descripcion_origen = 'ia_revisada' where slug = 'teatro-circo-price';
update public.espacios_escenicos set direccion = 'Gran Vía 78', codigo_postal = '28013', accesibilidad = 'parcial', wikidata_id = 'Q6139667', arquitecto = 'Pedro Muguruza / Casto Fernández-Shaw', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Gran_V%C3%ADa_78%2C_Edificio_Coliseum.jpg/1280px-Gran_V%C3%ADa_78%2C_Edificio_Coliseum.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Gran_V%C3%ADa_78,_Edificio_Coliseum.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Totemkin', descripcion = 'Teatro de la Gran Vía en el edificio Coliseum, proyectado por Pedro Muguruza y Casto Fernández-Shaw. Es uno de los escenarios habituales de los grandes musicales en Madrid.', descripcion_origen = 'ia_revisada' where slug = 'teatro-coliseum';
update public.espacios_escenicos set direccion = 'Calle Tagoror 4', wikidata_id = 'Q46836306', anio_inauguracion = 1912, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Teatro_Consistorial_de_G%C3%A1ldar_%284836640349%29.jpg/1280px-Teatro_Consistorial_de_G%C3%A1ldar_%284836640349%29.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Consistorial_de_G%C3%A1ldar_(4836640349).jpg', imagen_licencia = 'CC BY-SA 2.0', imagen_autor = 'Juan Ramón Rodríguez Sosa', descripcion = 'Teatro histórico de Gáldar, en el norte de Gran Canaria, inaugurado en 1912. Acoge teatro, música y actividades culturales del municipio.', descripcion_origen = 'ia_revisada' where slug = 'teatro-consistorial-de-galdar';
update public.espacios_escenicos set direccion = 'Calle Viera y Clavijo 11', wikidata_id = 'Q11951073', arquitecto = 'Miguel Martín-Fernández de la Torre', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Teatro_Cuy%C3%A1s_01.jpg/1280px-Teatro_Cuy%C3%A1s_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Cuy%C3%A1s_01.jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Beta15', descripcion = 'Teatro de la calle Viera y Clavijo, en Las Palmas de Gran Canaria, levantado en los años treinta con proyecto de Miguel Martín-Fernández de la Torre. Tras una larga etapa como cine, reabrió como teatro a finales de los noventa y hoy es uno de los principales escenarios de la isla.', descripcion_origen = 'ia_revisada' where slug = 'teatro-cuyas';
update public.espacios_escenicos set direccion = 'Calle de Fernández de los Ríos 42', codigo_postal = '28015', wikidata_id = 'Q3982248', aforo = 504, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/La_Abad%C3%ADa.jpg/1280px-La_Abad%C3%ADa.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:La_Abad%C3%ADa.jpg', imagen_licencia = 'CC BY 3.0', imagen_autor = 'Paco Manzano', descripcion = 'Teatro fundado por José Luis Gómez en una antigua iglesia del barrio de Chamberí y abierto en 1995. Combina programación propia, formación y creación.', descripcion_origen = 'ia_revisada' where slug = 'teatro-de-la-abadia';
update public.espacios_escenicos set direccion = 'Plaza de Cristóbal Colón 8', codigo_postal = '28220', telefono = '+34 91 6349119', accesibilidad = 'si', titularidad = 'publica' where slug = 'teatro-de-la-casa-de-la-cultura-carmen-conde';
update public.espacios_escenicos set direccion = 'Calle del Príncipe 14', codigo_postal = '28012', telefono = '+34 91 532 79 27', accesibilidad = 'si', titularidad = 'publica', wikidata_id = 'Q10378974', anio_inauguracion = 1875, arquitecto = 'Agustín Ortíz de Villajos / Francisco Andrés Octavio', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Teatro_de_la_Comedia_Madrid_2008_2.jpg/1280px-Teatro_de_la_Comedia_Madrid_2008_2.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_de_la_Comedia_Madrid_2008_2.jpg', imagen_licencia = 'CC BY 2.5', imagen_autor = 'Andreas Praefcke', descripcion = 'Teatro de la calle del Príncipe inaugurado en 1875 y sede de la Compañía Nacional de Teatro Clásico. Reabrió en 2015 tras una larga rehabilitación.', descripcion_origen = 'ia_revisada' where slug = 'teatro-de-la-comedia';
update public.espacios_escenicos set direccion = 'Calle de Jovellanos 4', codigo_postal = '28014', telefono = '+34 91 524 54 00', accesibilidad = 'si', wikidata_id = 'Q3321632', anio_inauguracion = 1856, arquitecto = 'José Espelius / Jerónimo de la Gándara / José María Guallart', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Teatro_de_la_Zarzuela_%28Madrid%29_02.jpg/1280px-Teatro_de_la_Zarzuela_%28Madrid%29_02.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_de_la_Zarzuela_(Madrid)_02.jpg', imagen_licencia = 'CC BY-SA 3.0 es', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Inaugurado en 1856 para dar casa al género lírico español, del que toma su nombre. Es un teatro público del Ministerio de Cultura (INAEM) dedicado a la zarzuela, la música y la danza.', descripcion_origen = 'ia_revisada' where slug = 'teatro-de-la-zarzuela';
update public.espacios_escenicos set accesibilidad = 'si', descripcion = 'Escenario de títeres en el parque del Retiro, con funciones para público familiar.', descripcion_origen = 'ia_revisada' where slug = 'teatro-de-titeres-de-el-retiro';
update public.espacios_escenicos set direccion = 'Calle de Zurita 20', codigo_postal = '28012', telefono = '+34 91 084 36 92', email = 'info@teatrodelbarrio.com', accesibilidad = 'parcial', wikidata_id = 'Q25400165', anio_inauguracion = 2013, descripcion = 'Teatro gestionado como cooperativa cultural en el barrio de Lavapiés, abierto en 2013.', descripcion_origen = 'ia_revisada' where slug = 'teatro-del-barrio';
update public.espacios_escenicos set direccion = 'Glorieta de Europa', telefono = '+34 91 6645064', wikidata_id = 'Q16913158', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/M%C3%B3stoles_-_Teatro_del_Bosque_13.jpg/1280px-M%C3%B3stoles_-_Teatro_del_Bosque_13.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:M%C3%B3stoles_-_Teatro_del_Bosque_13.jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Zarateman' where slug = 'teatro-del-bosque';
update public.espacios_escenicos set direccion = 'Avenida del Rey Juan Carlos I 10', codigo_postal = '28913', accesibilidad = 'no' where slug = 'teatro-egaleo';
update public.espacios_escenicos set direccion = 'Calle Pozuelo de Zarzón 3', codigo_postal = '28005' where slug = 'teatro-encantado';
update public.espacios_escenicos set direccion = 'Calle del Calvario 21', codigo_postal = '28012' where slug = 'teatro-espada-de-madera';
update public.espacios_escenicos set telefono = '+34 91 318 47 00', redes = '{"facebook": "https://www.facebook.com/teatroespanolmadrid", "x": "https://twitter.com/teatroespanol"}'::jsonb, wikidata_id = 'Q3891573', arquitecto = 'Juan de Villanueva / Luis Bellido / Enrique Colás Hontán / Pablo Aranda Sánchez', aforo = 763, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Teatro_Espa%C3%B1ol_%28Madrid%29_01.jpg/1280px-Teatro_Espa%C3%B1ol_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Espa%C3%B1ol_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro municipal de la plaza de Santa Ana, levantado en el solar del antiguo Corral del Príncipe, activo desde 1583. Es uno de los escenarios de referencia del teatro en español y pertenece a la red de teatros del Ayuntamiento de Madrid.', descripcion_origen = 'ia_revisada' where slug = 'teatro-espanol';
update public.espacios_escenicos set telefono = '+34 912 08 04 61', email = 'tglorca@ayto-getafe.org' where slug = 'teatro-federico-garcia-lorca';
update public.espacios_escenicos set accesibilidad = 'si', wikidata_id = 'Q6139714', arquitecto = 'Manuel Herrero Palacios', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Centro_Cultural_de_la_Villa_de_Madrid_01.jpg/1280px-Centro_Cultural_de_la_Villa_de_Madrid_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Centro_Cultural_de_la_Villa_de_Madrid_01.jpg', imagen_licencia = 'CC BY 2.0', imagen_autor = 'Untipografico', descripcion = 'Centro cultural municipal situado bajo la plaza de Colón, que lleva el nombre del actor, director y académico Fernando Fernán Gómez. Programa teatro, danza, música y exposiciones.', descripcion_origen = 'ia_revisada' where slug = 'teatro-fernan-gomez';
update public.espacios_escenicos set direccion = 'Calle del Pez 10', codigo_postal = '28004', telefono = '+34 911 592 005', email = 'reservas@teatroflamencomadrid.com' where slug = 'teatro-flamenco-madrid';
update public.espacios_escenicos set direccion = 'Calle de Galileo 39', codigo_postal = '28015' where slug = 'teatro-galileo';
update public.espacios_escenicos set direccion = 'Calle de Fortunata y Jacinta 17', telefono = '+34 91 032 16 19' where slug = 'teatro-gran-maestre';
update public.espacios_escenicos set direccion = 'Gran Vía 66', telefono = '+34 91 541 55 69', accesibilidad = 'si', wikidata_id = 'Q8346271', arquitecto = 'Germán Álvarez de Sotomayor y Castro' where slug = 'teatro-gran-via';
update public.espacios_escenicos set direccion = 'Plaza Isla de la Madera 2', wikidata_id = 'Q4891034', anio_inauguracion = 1851, arquitecto = 'Manuel de Oraá', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Teatro_Guimera.jpg/1280px-Teatro_Guimera.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Guimera.jpg', imagen_licencia = 'Dominio público', imagen_autor = 'kallerna', descripcion = 'Uno de los teatros más antiguos de Canarias, inaugurado en 1851 en Santa Cruz de Tenerife con proyecto de Manuel de Oraá. Lleva el nombre del dramaturgo Ángel Guimerá, nacido en la ciudad, y programa teatro, música y danza.', descripcion_origen = 'ia_revisada' where slug = 'teatro-guimera';
update public.espacios_escenicos set direccion = 'Calle de Martínez Izquierdo 20', codigo_postal = '28028' where slug = 'teatro-guindalera';
update public.espacios_escenicos set wikidata_id = 'Q5946189', descripcion = 'Antiguo cine de Las Palmas de Gran Canaria reconvertido en teatro y gestionado por el Gobierno de Canarias. Programa teatro, danza, música y cine.', descripcion_origen = 'ia_revisada' where slug = 'teatro-guiniguada';
update public.espacios_escenicos set direccion = 'Calle del Barquillo 24', codigo_postal = '28004', telefono = '+34 915 21 02 12', email = 'info@teatroinfantaisabel.es', wikidata_id = 'Q6139753', anio_inauguracion = 1913, arquitecto = 'Eladio Laredo', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Teatro_Infanta_Isabel_%28Madrid%29_01.jpg/1280px-Teatro_Infanta_Isabel_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Infanta_Isabel_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro de la calle del Barquillo inaugurado en 1913 con proyecto de Eladio Laredo, dedicado sobre todo a la comedia contemporánea.', descripcion_origen = 'ia_revisada' where slug = 'teatro-infanta-isabel';
update public.espacios_escenicos set direccion = 'Calle de Velarde 15', codigo_postal = '28004', email = 'info@intemperieteatro.com', accesibilidad = 'no' where slug = 'teatro-intemperie';
update public.espacios_escenicos set telefono = '+34 91 539 62 36', email = 'info@karpasteatro.com', accesibilidad = 'parcial' where slug = 'teatro-karpas';
update public.espacios_escenicos set direccion = 'Calle de Ercilla 15', codigo_postal = '28005', wikidata_id = 'Q96184374' where slug = 'teatro-la-encina';
update public.espacios_escenicos set direccion = 'Plaza de la Cebada 2', codigo_postal = '28005', telefono = '+34 913 65 28 35', accesibilidad = 'no', wikidata_id = 'Q3323525', arquitecto = 'Pedro Muguruza', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Teatro_La_Latina_DSCN1132.JPG/1280px-Teatro_La_Latina_DSCN1132.JPG', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_La_Latina_DSCN1132.JPG', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Museo8bits', descripcion = 'Teatro de la plaza de la Cebada, en el barrio de La Latina, con edificio proyectado por Pedro Muguruza. Es uno de los escenarios comerciales con más tradición de Madrid, ligado a la revista y la comedia.', descripcion_origen = 'ia_revisada' where slug = 'teatro-la-latina';
update public.espacios_escenicos set direccion = 'Corredera Baja de San Pablo 15', codigo_postal = '28004', accesibilidad = 'no', wikidata_id = 'Q6139776', anio_inauguracion = 1880, arquitecto = 'Carlos Velasco Peinado / Jerónimo Pedro Mathet Rodríguez', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Teatro_Lara_%28Madrid%29_01.jpg/1280px-Teatro_Lara_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Lara_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Uno de los teatros más antiguos de Madrid en activo, inaugurado en 1880 en la Corredera Baja de San Pablo. Por su decoración interior se le conoce como la «bombonera de don Cándido», en referencia a su fundador, Cándido Lara.', descripcion_origen = 'ia_revisada' where slug = 'teatro-lara';
update public.espacios_escenicos set wikidata_id = 'Q950052', anio_inauguracion = 1915, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/5/5a/LagunaTeatro02.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:LagunaTeatro02.jpg', imagen_licencia = 'CC BY 3.0', imagen_autor = 'Koppchen', descripcion = 'Teatro de San Cristóbal de La Laguna inaugurado en 1915, de estilo ecléctico con elementos modernistas. Rehabilitado a comienzos de este siglo, es el principal escenario municipal de la ciudad.', descripcion_origen = 'ia_revisada' where slug = 'teatro-leal';
update public.espacios_escenicos set direccion = 'Gran Vía 57', accesibilidad = 'no', wikidata_id = 'Q6676154', anio_inauguracion = 1947, aforo = 1453, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/6/66/Patio_de_butacas..jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Patio_de_butacas..jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Webstage', descripcion = 'Gran teatro de la Gran Vía situado en el edificio Lope de Vega, levantado a finales de los años cuarenta. Con más de mil cuatrocientas localidades, se dedica a los grandes musicales.', descripcion_origen = 'ia_revisada' where slug = 'teatro-lope-de-vega';
update public.espacios_escenicos set wikidata_id = 'Q6139794', anio_inauguracion = 1918, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Teatro_Maravillas_0200.JPG/1280px-Teatro_Maravillas_0200.JPG', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Maravillas_0200.JPG', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Museo8bits', descripcion = 'Teatro del barrio de Malasaña inaugurado en 1918.', descripcion_origen = 'ia_revisada' where slug = 'teatro-maravillas';
update public.espacios_escenicos set direccion = 'Calle de Tamayo y Baus 4', codigo_postal = '28004', telefono = '+34 913 102949', accesibilidad = 'si', titularidad = 'publica', wikidata_id = 'Q5399324', anio_inauguracion = 1885, arquitecto = 'Agustín Ortíz de Villajos / Casto Fernández-Shaw / Pablo Aranda Sánchez', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Teatro_Mar%C3%ADa_Guerrero_%28Madrid%29_01.jpg/1280px-Teatro_Mar%C3%ADa_Guerrero_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Mar%C3%ADa_Guerrero_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0 es', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Inaugurado en 1885 como Teatro de la Princesa, es sede del Centro Dramático Nacional. Lleva el nombre de la actriz María Guerrero, que lo dirigió con su compañía.', descripcion_origen = 'ia_revisada' where slug = 'teatro-maria-guerrero';
update public.espacios_escenicos set wikidata_id = 'Q9082161', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Teatro_Marquina_%28Madrid%29_01.jpg/1280px-Teatro_Marquina_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Marquina_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro del centro de Madrid que lleva el nombre del dramaturgo y poeta Eduardo Marquina.', descripcion_origen = 'ia_revisada' where slug = 'teatro-marquina';
update public.espacios_escenicos set direccion = 'Calle Pedro Martín Hernández', codigo_postal = '38750' where slug = 'teatro-monterrey';
update public.espacios_escenicos set wikidata_id = 'Q3516764', anio_inauguracion = 1922, arquitecto = 'Teodoro de Anasagasti', aforo = 1600, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Monumental_Cinema-Atocha-01.jpg/1280px-Monumental_Cinema-Atocha-01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Monumental_Cinema-Atocha-01.jpg', imagen_licencia = 'CC BY 3.0', imagen_autor = 'Tamorlan', descripcion = 'Teatro de la calle de Atocha proyectado por Teodoro de Anasagasti e inaugurado en los años veinte. Es sede de la Orquesta y Coro de RTVE.', descripcion_origen = 'ia_revisada' where slug = 'teatro-monumental';
update public.espacios_escenicos set direccion = 'Plaza Santo Domingo', codigo_postal = '35260' where slug = 'teatro-municipal-de-aguimes';
update public.espacios_escenicos set direccion = 'Avenida de los Príncipes de España 2', codigo_postal = '28823' where slug = 'teatro-municipal-de-coslada';
update public.espacios_escenicos set wikidata_id = 'Q129412124', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Teatro_municipal_de_San_Bartolom%C3%A9_%2829_de_julio_de_2019%2C_San_Bartolom%C3%A9%2C_Lanzarote%29.jpg/1280px-Teatro_municipal_de_San_Bartolom%C3%A9_%2829_de_julio_de_2019%2C_San_Bartolom%C3%A9%2C_Lanzarote%29.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_municipal_de_San_Bartolom%C3%A9_(29_de_julio_de_2019,_San_Bartolom%C3%A9,_Lanzarote).jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Discasto' where slug = 'teatro-municipal-de-san-bartolome';
update public.espacios_escenicos set direccion = 'Calle del Paso de Villamanrique 3', accesibilidad = 'si', titularidad = 'publica' where slug = 'teatro-municipal-de-vallecas';
update public.espacios_escenicos set direccion = 'Plaza del Carmen 1', telefono = '+34 91 523 21 28', wikidata_id = 'Q2879450', anio_inauguracion = 1930, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Teatro_Mu%C3%B1oz_Seca_-_Plaza_del_Carmen.jpg/1280px-Teatro_Mu%C3%B1oz_Seca_-_Plaza_del_Carmen.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Mu%C3%B1oz_Seca_-_Plaza_del_Carmen.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Tamorlan', descripcion = 'Teatro de la plaza del Carmen, en el centro de Madrid, inaugurado en 1930 y dedicado al dramaturgo Pedro Muñoz Seca.', descripcion_origen = 'ia_revisada' where slug = 'teatro-munoz-seca';
update public.espacios_escenicos set direccion = 'Calle del Norte 9', codigo_postal = '28015', email = 'contacto@nuevenorte.com' where slug = 'teatro-nueve-norte';
update public.espacios_escenicos set direccion = 'Plaza de Tirso de Molina 1', codigo_postal = '28012', telefono = '+34 918 554 162', email = 'atencioncliente@summummusic.com', wikidata_id = 'Q6139839', anio_inauguracion = 1932, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Teatro_Nuevo_Apolo_%28Madrid%29_01.jpg/1280px-Teatro_Nuevo_Apolo_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Nuevo_Apolo_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro de la plaza de Tirso de Molina con edificio de 1932, dedicado sobre todo a musicales y espectáculos de gran formato.', descripcion_origen = 'ia_revisada' where slug = 'teatro-nuevo-apolo';
update public.espacios_escenicos set direccion = 'Calle de Embajadores 9', codigo_postal = '28012', titularidad = 'privada', wikidata_id = 'Q7691940', anio_inauguracion = 1925, arquitecto = 'Teodoro de Anasagasti', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Teatro_Pav%C3%B3n_%28Madrid%29_01.jpg/1280px-Teatro_Pav%C3%B3n_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Pav%C3%B3n_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro de estilo art déco en la calle de Embajadores, proyectado por Teodoro de Anasagasti e inaugurado en 1925.', descripcion_origen = 'ia_revisada' where slug = 'teatro-pavon';
update public.espacios_escenicos set direccion = 'Plaza Stagno 1', wikidata_id = 'Q206404', anio_inauguracion = 1890, arquitecto = 'Francisco Jareño y Alarcón / Miguel Martín-Fernández de la Torre', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Teatro_P%C3%A9rez_Gald%C3%B3s_2014.jpg/1280px-Teatro_P%C3%A9rez_Gald%C3%B3s_2014.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_P%C3%A9rez_Gald%C3%B3s_2014.jpg', imagen_licencia = 'CC BY 3.0', imagen_autor = 'Koppchen', descripcion = 'Principal teatro de Las Palmas de Gran Canaria, inaugurado en 1890 junto al barranco de Guiniguada. Tras el incendio de 1918 fue reconstruido con proyecto de Miguel Martín-Fernández de la Torre y decoración de su hermano, el pintor Néstor. Acoge temporadas de ópera, danza, música y teatro.', descripcion_origen = 'ia_revisada' where slug = 'teatro-perez-galdos';
update public.espacios_escenicos set wikidata_id = 'Q6139857', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Teatro_Pradillo_DSCF0497.JPG/1280px-Teatro_Pradillo_DSCF0497.JPG', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Pradillo_DSCF0497.JPG', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Museo8bits' where slug = 'teatro-pradillo';
update public.espacios_escenicos set direccion = 'Calle de las Tres Cruces 8', wikidata_id = 'Q66135427', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Madrid_-_48415080961.jpg/1280px-Madrid_-_48415080961.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Madrid_-_48415080961.jpg', imagen_licencia = 'CC BY 2.0', imagen_autor = 'erikccooper' where slug = 'teatro-principe-gran-via';
update public.espacios_escenicos set direccion = 'Calle de Bravo Murillo 18', codigo_postal = '28015', telefono = '+34 91445 7193' where slug = 'teatro-quevedo';
update public.espacios_escenicos set direccion = 'Plaza de Isabel II', codigo_postal = '28013', telefono = '+34 902 24 48 48', email = 'info@teatroreal.es', wikidata_id = 'Q211250', anio_inauguracion = 1850, arquitecto = 'Antonio López Aguado / Custodio Teodoro Moreno', aforo = 1958, imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Teatro_Real_de_Madrid_2025.jpg/1280px-Teatro_Real_de_Madrid_2025.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Real_de_Madrid_2025.jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Fernando', descripcion = 'Teatro de ópera situado frente al Palacio Real, inaugurado en 1850. Tras una larga etapa como sala de conciertos, reabrió como teatro de ópera en 1997 y es hoy el principal coliseo lírico de España.', descripcion_origen = 'ia_revisada' where slug = 'teatro-real';
update public.espacios_escenicos set direccion = 'Carrera de San Jerónimo 24', telefono = '+34 91 369 22 88', email = 'info@elteatroreinavictoria.com', wikidata_id = 'Q6139886', anio_inauguracion = 1916, arquitecto = 'José Espelius', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Teatro_Reina_Victoria_%28Madrid%29_01.jpg/1280px-Teatro_Reina_Victoria_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Reina_Victoria_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Teatro de la Carrera de San Jerónimo inaugurado en 1916, obra del arquitecto José Espelius.', descripcion_origen = 'ia_revisada' where slug = 'teatro-reina-victoria';
update public.espacios_escenicos set direccion = 'Gran Vía 54', accesibilidad = 'no', wikidata_id = 'Q5769684' where slug = 'teatro-rialto';
update public.espacios_escenicos set direccion = 'Plaza de San Pol de Mar 1', codigo_postal = '28008', wikidata_id = 'Q45911498', arquitecto = 'Fernando Moreno Barberá / Rafael de la Joya Castro' where slug = 'teatro-san-pol';
update public.espacios_escenicos set direccion = 'Calle de Serrano 104', codigo_postal = '28006' where slug = 'teatro-serrano';
update public.espacios_escenicos set direccion = 'Gran Vía 70', codigo_postal = '28013', telefono = '+34 91 524 25 03', accesibilidad = 'parcial', wikidata_id = 'Q37469082' where slug = 'teatro-sofia';
update public.espacios_escenicos set wikidata_id = 'Q136100837', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Teatro_Uni%C3%B3n_Tejina.jpg/1280px-Teatro_Uni%C3%B3n_Tejina.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Uni%C3%B3n_Tejina.jpg', imagen_licencia = 'CC BY-SA 4.0', imagen_autor = 'Mentxuwiki' where slug = 'teatro-union-tejina';
update public.espacios_escenicos set direccion = 'Plaza de Lavapiés', codigo_postal = '28012', titularidad = 'publica', wikidata_id = 'Q7691967', arquitecto = 'Ángela García de Paredes', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Teatro_Valle-Incl%C3%A1n_%28Madrid%29_01.jpg/1280px-Teatro_Valle-Incl%C3%A1n_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatro_Valle-Incl%C3%A1n_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Sede del Centro Dramático Nacional en la plaza de Lavapiés, levantada en el solar del antiguo cine Olimpia con proyecto de Ángela García de Paredes. Reúne varias salas dedicadas sobre todo a la dramaturgia contemporánea.', descripcion_origen = 'ia_revisada' where slug = 'teatro-valle-inclan';
update public.espacios_escenicos set direccion = 'Calle Méndez Núñez 36', codigo_postal = '38002' where slug = 'teatro-victoria';
update public.espacios_escenicos set direccion = 'Calle del Pez 17', codigo_postal = '28004', telefono = '+34 91 522 88 34' where slug = 'teatro-victoria-madrid';
update public.espacios_escenicos set titularidad = 'publica' where slug = 'teatro-villa-de-mostoles';
update public.espacios_escenicos set wikidata_id = 'Q6140051', anio_inauguracion = 2009, arquitecto = 'Juan Navarro Baldeweg', imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Teatros_del_Canal_%28Madrid%29_01.jpg/1280px-Teatros_del_Canal_%28Madrid%29_01.jpg', imagen_fuente_url = 'https://commons.wikimedia.org/wiki/File:Teatros_del_Canal_(Madrid)_01.jpg', imagen_licencia = 'CC BY-SA 3.0', imagen_autor = 'Luis García (Zaqarbal)', descripcion = 'Complejo escénico de la Comunidad de Madrid inaugurado en 2009, obra de Juan Navarro Baldeweg. Reúne varias salas y es sede del Centro de Danza Canal.', descripcion_origen = 'ia_revisada' where slug = 'teatros-del-canal';
update public.espacios_escenicos set telefono = '+34 910 075 684', accesibilidad = 'si' where slug = 'teatros-luchana';
update public.espacios_escenicos set direccion = 'Calle de Emilio Ferrari 33', codigo_postal = '28017' where slug = 'urban-teatro';
update public.espacios_escenicos set descripcion = 'Principal sala de conciertos de Madrid, inaugurada en 1988 y sede de la Orquesta y Coro Nacionales de España.', descripcion_origen = 'ia_revisada' where slug = 'auditorio-nacional-de-musica';
update public.espacios_escenicos set descripcion = 'Centro internacional de artes vivas situado en Matadero Madrid, el antiguo matadero municipal junto al río Manzanares.', descripcion_origen = 'ia_revisada' where slug = 'naves-matadero';

